r-p-s_app/RPS_game/models.py
from . import db
from sqlalchemy.sql import func


class User(db.Model):
    __tablename__ = "User"
    id = db.Column(db.Integer, primary_key=True)
    cr_points = db.Column(db.Integer)


class Game(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    gamer = db.Column(db.Integer, db.ForeignKey("User.id"))
    result = db.Column(db.String(20))
    nb_cr = db.Column(db.Integer)
    date = db.Column(db.DateTime(timezone=True), default=func.now())


def add_rec(note):
    db.session.add(note)
    db.session.commit()


def edit_rec(note):
    db.session.commit()


def max_id(key):
    x = db.session.query(key).all()
    return max(x)

r-p-s_app/RPS_game/__init__.py
import os
from flask_sqlalchemy import SQLAlchemy
from dotenv import load_dotenv
from flask import Flask
from RPS_game.routes import game_routes

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    load_dotenv()
    from .models import User, Game

    app_env = os.environ.get("FLASK_ENV", "development")
    secret_key = os.environ.get("SECRET_KEY", "dfl;gv,' z l")
    testing = False

    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(ENV=app_env, SECRET_KEY=secret_key, TESTING=testing)

    app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{DB_NAME}"
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    app.register_blueprint(game_routes)

    db.init_app(app)
    create_database(app)

    return app


def create_database(app):
    if not os.path.exists("website/" + DB_NAME):
        db.create_all(app=app)
        print("Created Database!")

r-p-s_app/RPS_game/routes.py
from datetime import datetime, timedelta
from flask import Blueprint, request, render_template, session, flash
from game_utils.rock_paper_scissors import *
from sqlalchemy.sql.expression import func

game_routes = Blueprint("game_routes", __name__)


@game_routes.route("/")
def index():
    print("VISITING THE START PAGE")
    return render_template("start.html")


@game_routes.route("/choose", methods=["GET", "POST"])
def New_Session(choice=None):

    from .models import User, add_rec, max_id

    new_user = User(cr_points=10)
    print(new_user)
    add_rec(new_user)
    user = User.query.get(max_id(User.id))
    result = {
        "have_credits": True,
        "user_choice": "",
        "computer_choice": "",
        "results_message": "",
        "cr_points": "",
        "user_id": "",
    }

    return render_template("choose.html", credits=user.cr_points, user=user.id)


@game_routes.route("/game", methods=["GET", "POST"])
def game(choice=None):
    from .models import User, Game, add_rec, max_id

    options = ["rock", "paper", "scissors"]
    # CAPTURE INPUTS
    game_stat = Game()
    user = User.query.get(max_id(User.id))
    if user.cr_points > 2:
        have_credits = True
        game_stat.nb_cr = user.cr_points
        user.cr_points -= 3

        add_rec(user)
        if "choice" in request.args:
            user_choice = request.args["choice"]
        elif "choice" in request.values:
            user_choice = request.values["choice"]
        else:
            user_choice = "rock"

        if user_choice not in options:
            user_choice = "rock"

        # PROCESS INPUTS
        computer_choice = random_choice(options)
        winning_choice = determine_winner(user_choice, computer_choice)

        if winning_choice:
            if winning_choice == user_choice:
                results_message = "WYGRANA!!"
                user.cr_points += 4
                add_rec(user)
            elif winning_choice == computer_choice:
                results_message = "Porażka..."
        else:
            results_message = "REMIS"
            user.cr_points += 3

        game_stat.gamer = user.id
        game_stat.result = results_message
        add_rec(game_stat)

        if user_choice == "rock":
            user_choice = "kamień"
        elif user_choice == "paper":
            user_choice = "papier"
        elif user_choice == "scissors":
            user_choice = "nożyce"
        if computer_choice == "rock":
            computer_choice = "kamień"
        elif computer_choice == "paper":
            computer_choice = "papier"
        elif computer_choice == "scissors":
            computer_choice = "nożyce"

        result = {
            "have_credits": have_credits,
            "user_choice": user_choice,
            "computer_choice": computer_choice,
            "results_message": results_message,
            "cr_points": user.cr_points,
            "user_id": user.id,
        }

    else:
        flash(
            "Za mało kredytów. Po wciśnięciu przycisku Dodaj punkty do dyspozycji otrzymasz 10 kredytów",
            category="success",
        )
        result = {
            "have_credits": False,
            "user_choice": "",
            "computer_choice": "",
            "results_message": "",
            "cr_points": user.cr_points,
            "user_id": user.id,
        }
    return render_template(
        "game.html",
        have_credits=result["have_credits"],
        user_choice=result["user_choice"],
        computer_choice=result["computer_choice"],
        results_message=result["results_message"],
        credits=result["cr_points"],
        user=result["user_id"],
        result=result,
    )


@game_routes.route("/add_cr", methods=["GET", "POST"])
def add_cr():
    from .models import User, edit_rec, max_id

    user = User.query.get(max_id(User.id))
    user.cr_points = 10
    edit_rec(user)
    return render_template(
        "game.html", have_credits=True, credits=user.cr_points, user=user.id
    )


@game_routes.route("/game_data", methods=["GET", "POST"])
def game_data():
    from .models import Game

    if request.method == "POST":
        filter_date = request.form.get("date")
        return render_template(
            "game_data.html",
            query=Game.query.filter(func.date(Game.date) == filter_date).all(),
        )
    return render_template("game_data.html", query=Game.query.all())

r-p-s_app/RPS_game/templates/choose.html
{% extends "layout.html" %}

{% block title %}
  <title>Wybierz | Papier kamień i nożyce</title>
  
{% endblock %}

{% block content %}
  <h2>Gracz nr:  {{ user }}</h2>
  <form action="/game" method="POST">

    <label>Wybierz jedną z opcji:</label>
    <select name="choice">
      <option value="rock">Kamień</option>
      <option value="paper">Papier</option>
      <option value="scissors">Nożyce</option>
    </select>

    <button onClick="game()">Zatwierdź</button>

    <h2>Dane gry</h2>
    <p>kredyty: {{ credits }}</p>

  </form>
{% endblock %}

r-p-s_app/RPS_game/templates/game.html
{% extends "layout.html" %}

{% block title %}
  <title>Gra | Papier kamień i nożyce</title>
  
{% endblock %}

{% block content %}
  <h2>Gracz nr:  {{ user }}</h2>
  <form action="/game" method="POST">

    <label>Wybierz jedną z opcji:</label>
    <select name="choice">
      <option value="rock">Kamień</option>
      <option value="paper">Papier</option>
      <option value="scissors">Nożyce</option>
    </select>

    <button onClick="game()">Zatwierdź</button>

    <h2>Dane gry</h2>
    {% if have_credits %}
      <p>Gracz wybrał: {{ user_choice }}</p>
      <p>Komputer wybrał: {{ computer_choice }}</p>
      <p>Wynik: {{ results_message }}</p>
      <p>Kredyty: {{ credits }}</p>
    {% else %}
      <p>Kredyty: {{ credits }}</p>
      <button type="button" onclick="window.location.href='{{ url_for( 'game_routes.add_cr') }}';">Dodaj kredyty</button>
    {% endif %}
    <button type="button" onclick="window.location.href='{{ url_for( 'game_routes.game_data') }}';">HIstoria gier</button>

  </form>

{% endblock %}

r-p-s_app/RPS_game/templates/game_data.html
{% extends "layout.html" %}

{% block title %}
<title>DB | Papier kamień i nożyce</title>
{% endblock %}

{% block content %}
  <h2>Start</h2>

  <h1 align="center">Historia gier</h1>

  <form method="POST">
    <h3 align="center">Wybierz datę</h3>
    <div class="form-group">
      <label for="date"> </label>
      <input
        type="date"
        class="form-control"
        id="date"
        name="date"
        placeholder="data"
      />
    </div>
    <button type="submit" class="btn btn-primary">Zatwierdź</button>
  </form>
  <style>
 
    td {
           width: 150px;
           text-align: center;
           border: 1px solid black;
           padding: 5px;
         }
         
   </style>
   <table align="center">
     <thead>
       <tr>
           <th>Nr.</th>
           <th>Gracz</th>
           <th>Wynik</th>
           <th>Liczba punktów przed rozgrywką</th>
           <th>data rozgrywki</th>
       </tr>
       </thead>    
       <tbody>
        {% for id in query %}    
               <tr>
                   <td>{{id.id}}</td>
                   <td>{{id.gamer}}</td>
                   <td>{{id.result}}</td>
                   <td>{{id.nb_cr}}</td>
                   <td>{{id.date}}</td>
               </tr>
           {% endfor %}
       </tbody>
   </table>
   <button type="button" onclick="window.location.href='{{ url_for( 'game_routes.game') }}';">Wróć</button>

{% endblock %}

r-p-s_app/RPS_game/templates/layout.html
<!doctype html>
<html>
  <head>
    {% block title %}
      <title>Papier kamień i nożyce</title>
    {% endblock %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    <div class="container">

      <!-- HEADER / NAV -->
      <div id="nav">
        <h1><a href="/">Papier kamień i nożyce</a></h1>
      </div>

      <hr>

      <!-- PAGE CONTENTS -->
      <div id="content">
        {% block content %}
        {% endblock %}
      </div>

     
    </div>

    <!-- JAVASCRIPT SECTION -->
    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript">
      
        $().alert('close')

    </script>
  </body>
</html>

r-p-s_app/RPS_game/templates/start.html
{% extends "layout.html" %}

{% block title %}
  <title>Start | Papier kamień i nożyce</title>
{% endblock %}

{% block content %}
  <h2>Start</h2>

  <form action="/choose" method="POST">
    <button align="center" onClick="New_Session()">Zagraj </button>  </form>
{% endblock %}